[package]
name = "ddnet-backcompat-proxy"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
arrayvec = "0.5.2"
libtw2-gamenet = { package = "libtw2-gamenet-ddnet", path = "../../../../libtw2/gamenet/ddnet" }
libtw2-packer = { path = "../../../../libtw2/packer" }
warn = "0.2.0"
